apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acme-cache-deployment
  labels:
    env: dev
    app: acme
    tier: acme-cache
spec:
  template:
    metadata:
      labels:
        app: acme-cache
    spec:
      containers:
      - name: acme-cache
        image: redis
        ports:
        - name: cache-port
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: acme-cache-service
spec:
  ports:
  - port: 6379
    targetPort: cache-port
    protocol: TCP
  selector:
    app: acme-cache
  type: LoadBalancer
