apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acme-database-deployment
  labels:
    env: dev
    app: acme
    tier: acme-database
spec:
  template:
    metadata:
      labels:
        app: acme-database
    spec:
      containers:
      - name: acme-database
        image: microsoft/mssql-server-linux
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Password@123"
        ports:
        - name: mssql-port
          containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: acme-database-service
spec:
  ports:
  - port: 1433
    targetPort: mssql-port
    protocol: TCP
  selector:
    app: acme-database
  type: LoadBalancer
